# -*- coding: utf-8 -*-
"""PetrackProject3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15U9uVd5HjSMx9YfX2hL-pkl_HImy78YV

# IMDB Sentiment Analysis (Kaggle Competition)

## Dataset
This dataset contains labeled movie reviews used to classify sentiment as positive or negative.

## Objective
Build a model that predicts sentiment from text using NLP techniques.

## Key Takeaways
- Text must be cleaned before modeling
- TF-IDF effectively converts text to numeric features
- Logistic Regression performs well on sentiment classification
- NLP models can be used in real-world review systems
"""

!pip install beautifulsoup4

"""Installing beautiful soup to remove any of the HTML tags. This got rid of special characthers using regular expressions, and converted all text to lowercase. This step was important to do because there was a need for clean data to make the learning model work."""

import pandas as pd

train = pd.read_csv("labeledTrainData.tsv", delimiter="\t")
test = pd.read_csv("testData.tsv", delimiter="\t")

train.head()

"""After uploading and previewing the data, the data shows a movie with an ID, Sentiment, and Review. The sentiment was either 1 or 0 aligning with the thought of 1 = good and 0 = bad."""

import re
from bs4 import BeautifulSoup

def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub("[^a-zA-Z]", " ", text)
    text = text.lower()
    return text

train["clean_review"] = train["review"].apply(clean_text)
test["clean_review"] = test["review"].apply(clean_text)

"""To help understand more about the sentiment, I created a chart to see if there was a big difference between good and bad movies. There was not a signifigant difference in either, actually almost zero difference."""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='sentiment', data=train)
plt.title("Sentiment Distribution")
plt.show()

"""After the finalization of cleaning the data, I converted the text into numerical features utilizing TF-IDF. This helps identify which words are important in each review while ignoring commonly used words."""

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(train["clean_review"])
y = train["sentiment"]

"""The next step I am going to be training and validation datasets and trained a Logistic Refgression Model. This model performed very well, acheiving an accuracy of about 88.34%, which shows it was effective."""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred))

"""Next, I used a confusion matrix. This matrix shows how many predictions were correct vs. incorrect. This confirmed that most reviews were classified accurately, with few errors."""

cm = confusion_matrix(y_val, y_pred)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.show()

"""I also wanted to look at the most common words in the dataset. The visualization showed frequent words like the, and, and movie, which helps give me insight into the language patterns in reviews."""

import numpy as np

words = vectorizer.get_feature_names_out()
counts = X.toarray().sum(axis=0)

top_words = pd.DataFrame({'word': words, 'count': counts})
top_words = top_words.sort_values(by='count', ascending=False).head(10)

sns.barplot(x='count', y='word', data=top_words)
plt.title("Top Words")
plt.show()

"""In addition to logistic regression, I also tested a random forrest model. This model performed slightly worse with an accuracy of 83.84%. This confirms the logistic regression test was a better choice for the problem."""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_val)

print("Random Forest Accuracy:", accuracy_score(y_val, rf_pred))

X_test = vectorizer.transform(test["clean_review"])

predictions = model.predict(X_test)

output = pd.DataFrame({
    "id": test["id"],
    "sentiment": predictions
})

output.to_csv("submission.csv", index=False)

from google.colab import files
files.download("submission.csv")

"""The very last step was uploading the trained model to Kaggle for the competition."""